### ISSUE TITLE
Add zotero directory.

### ISSUE THREAD

**Issue by katyhuff** [jbae11/europe_nuclear_paper#2]
There doesn't appear to be a zotero directory associated with this paper in the arfc group. Please add one.

**Comment by jbae11** [comment]
Oh, I had it in my personal library because I wasn't sure it this qualified for the ARFC library. Will do!

**Comment by katyhuff** [comment]
There's no lower bound for quality. If you want any potential for collaboration, it needs to be in the arfc group. In any case, any paper supported (even just at this 50% level) by arfc funds should be treated as an arfc paper, as it is an arfc product. If that doesn't seem appropriate, I'd be happy for us to talk as a group about whether that's a good cultural norm for the group.

**Comment by jbae11** [comment]
Makes sense! thanks
