### ISSUE TITLE
Edits in Paper Format

### ISSUE THREAD

**Issue by katyhuff** [jbae11/europe_nuclear_paper#7]
Hi @jbae11 : 
I left a marked-up version of this document on your desk .  I know you weren't ready for me to read this, but I was excited to read it and couldn't help myself. So I left some markups as suggestions for you to consider while you continue to draft the document. That seemed less pushy than a PR (which you might not be ready for at this stage, since you're still drafting). 

I'm leaving this as an open issue so you can reference it if/when you make any of the edits that I suggested. 

The first part looks good (grammatical and phrasing stuff mostly), and I know you're still in the sketchy draft stage for the latter part. I'm looking forward to the final product and I hope to be helpful!

**Comment by katyhuff** [comment]
Has these edits been handled? If so, please update this issue with a comment indicating when (e.g. commit, or PR #) and close it.

**Comment by jbae11** [comment]
It has been updated in the [commit 08e25a6b8b7b290ce4867dec00bfd02efa194eab](https://github.com/jbae11/europe_nuclear_paper/commit/08e25a6b8b7b290ce4867dec00bfd02efa194eab)
