### ISSUE TITLE
Never Reprocess vs Reprocess Till 2010 vs Continue Reprocessing

### ISSUE THREAD

**Issue by jbae11** [jbae11/europe_nuclear_paper#9]
# Fission Products and Minor Actinides
## Reprocessing Stops at 2010
![fp_ma_total_waste](https://cloud.githubusercontent.com/assets/20345275/25560281/7f9d8b40-2d15-11e7-9b99-55280dce3385.png)
## Reprocessing Continues
![fp_ma_total_waste](https://cloud.githubusercontent.com/assets/20345275/25560293/a30080d8-2d15-11e7-99e6-c7e6c7079ce7.png)

# Total Tailing
## Reprocessing Stops at 2010
![tailing_total_tailings](https://cloud.githubusercontent.com/assets/20345275/25560300/bee861da-2d15-11e7-81e4-03b53b2e9dac.png)
## Reprocessing Continues
![tailing_total_tailings](https://cloud.githubusercontent.com/assets/20345275/25560301/c4c79f26-2d15-11e7-807e-1a1329a4471f.png)
## Never Reprocess
![tails_total_waste](https://cloud.githubusercontent.com/assets/20345275/25560357/3d954c7c-2d17-11e7-80a7-db284e2b46ba.png)

# Reprocessed U
## Reprocessing Stops at 2010
![separations_total_stockpile](https://cloud.githubusercontent.com/assets/20345275/25560309/fa71bfbc-2d15-11e7-80c7-472a12e439bb.png)
## Reprocessing Continues
![separations_total_stockpile](https://cloud.githubusercontent.com/assets/20345275/25560307/eeb536e0-2d15-11e7-8f99-80c78d525a71.png)

# Total waste UOX
## Reprocessing Stops at 2010
![reactor_total_waste](https://cloud.githubusercontent.com/assets/20345275/25560314/0e237a50-2d16-11e7-8ce1-c15d45f3e7ee.png)
## Reprocessing Continues
![reactor_total_waste](https://cloud.githubusercontent.com/assets/20345275/25560315/12f9b10c-2d16-11e7-9b7d-9e90fe786ea9.png)
## Never Reprocess
![reactor_total_waste](https://cloud.githubusercontent.com/assets/20345275/25560360/4c17ccfc-2d17-11e7-93bf-5b4254acc597.png)

# Total Fuel Usage
## Reprocessing Stops at 2010
![total_fuel](https://cloud.githubusercontent.com/assets/20345275/25560323/798c1248-2d16-11e7-8aad-91ffa19dcd5e.png)
## Reprocessing Continues
![total_fuel](https://cloud.githubusercontent.com/assets/20345275/25560324/7d380f64-2d16-11e7-9e9a-d16cd3df6ff8.png)
## Never Reprocess
![total_fuel](https://cloud.githubusercontent.com/assets/20345275/25560363/51719a2a-2d17-11e7-81e2-23db84138611.png)

**Comment by jbae11** [comment]
@katyhuff

**Comment by katyhuff** [comment]
Cool. You have gotten my attention. Is there a question here, or is this just an "fyi?" This looks pretty reasonable to me (though, I suppose I would expect slightly more mox use... depends on the paramters of the fuel fab.. I'm not sure what I'm looking at.). Nice work!

**Comment by jbae11** [comment]
Oh the input files are [here](https://github.com/jbae11/cyclus_input_files)
This is kind of an 'fyi', the parameters are as follows:
separations extracts Uranium and Plutonium 99.8% (La Hague)
Mox is created using uranium tailing and Plutonium.

I do think that there's very little MOX being produced, 
but the capacity of the fuelfab is currently set as infinite ( there's still limits for the separations),
and all the plutonium is being used up to create mox.

I guess I want to ask you: 
1. I think the goal of the paper is to simply compare waste inventory from different scenarios.
What do you think is a good goal (objective) for this paper?
2. What other data from the simulation would you want to see? (Isotopics?)

**Comment by katyhuff** [comment]
Cool. 
Issues should, generally, be close-able. 

I think we're scheduled to talk about question 1 on Monday. Let's do that.

**Comment by katyhuff** [comment]
The answer to question 1 ([I asked you first](https://github.com/jbae11/europe_nuclear_paper/issues/8#issuecomment-297854292)) will inform question 2.

**Comment by jbae11** [comment]
This issue is closed because it is no longer relevant.
